-- File auto generated by purescript-bridge! --
module RSCoin.Core.Primitives where

import RSCoin.Core.Crypto.Signing (PublicKey)

import Data.Generic (class Generic)


data Address =
    Address {
      getAddress :: PublicKey
    }

derive instance genericAddress :: Generic Address

