#!/usr/bin/env bash

#### RSCoin demo ####

[ ! -d "~/.rscoin" ]      && mkdir ~/.rscoin 2>&1 > /dev/null
[ ! -f "~/.rscoin/key" ]  && cp rscoin-key ~/.rscoin/key

echo "I will start RSCoin demo in 10 seconds, it will erase the blockchain. Press ^C to cancel, <CR> to procede"

read -t 10

admin/cleanDB.sh
rm -rvf bank-db
rm -rvf wallet-db

read -n 1 -p "Press any key to start the demo"

####

_session="rscoin-demo"
tmux start-server\; has-session -t "$_session" 2>/dev/null

_wd="$(pwd)"
_post_hook_maybe=$([ -f "shell.nix" ] && echo "nix-shell")

TMUX="$(tmux new-session -d -s "$_session" -n project)"
tmux new-window -c "$_wd" -t "${_session}:1" -n build
tmux new-window -c "$_wd" -t "${_session}:2" -n git
tmux new-window -c "$_wd" -t "${_session}:3" -n mintette12
tmux new-window -c "$_wd" -t "${_session}:4" -n mintette34 
tmux new-window -c "$_wd" -t "${_session}:5" -n bank

tmux send-keys -t "${_session}:0" "cd src/" C-m
tmux send-keys -t "${_session}:0" "vim ." C-m
tmux send-keys -t "${_session}:2" "git log --graph --decorate --all -n7 | grep ." C-m
if [ ! -z "$_post_hook_maybe" ]; then
  for x in {2..5}; do
    tmux send-keys -t "${_session}:${x}" "$_post_hook_maybe" C-m
  done
fi

tmux send-keys       -t "${_session}:3" "admin/runAsMintette.sh 1" C-m
tmux split-window -h -t "${_session}:3"
tmux send-keys       -t "${_session}:3" "sleep 1; admin/runAsMintette.sh 2" C-m

tmux send-keys       -t "${_session}:4" "sleep 2; admin/runAsMintette.sh 3" C-m
tmux split-window -h -t "${_session}:4"
tmux send-keys       -t "${_session}:4" "sleep 3; admin/runAsMintette.sh 4" C-m

tmux send-keys       -t "${_session}:5" "sleep 7; admin/initBankUser.sh" C-m
tmux split-window -h -t "${_session}:5"
tmux send-keys       -t "${_session}:5" "sleep 6; stack $NIX_STACK exec rscoin-bank serve" C-m

tmux select-window -t 0

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t "${_session}"
else
  tmux -u switch-client -t "${_session}"
fi
