#!/usr/bin/env bash

#### RSCoin demo ####

[ ! -d "~/.rscoin" ]      && mkdir ~/.rscoin 2>&1 > /dev/null
[ ! -f "~/.rscoin/key" ]  && cp rscoin-key ~/.rscoin/key

echo "I will start RSCoin demo in 10 seconds, it will erase the blockchain. Press ^C to cancel, <CR> to procede"

read -t 10

admin/cleanDB.sh
rm -rvf bank-db
rm -rvf wallet-db
rm -rvf wallet-db-user
rm -rvf demouser1-db
rm -rvf demouser2-db
rm -rvf demouser1-gui-db
rm -rvf demouser2-gui-db

read -n 1 -p "Press any key to start the demo"

####

_session="rscoin-demo"
tmux start-server\; has-session -t "$_session" 2>/dev/null

_wd="$(pwd)"
#_post_hook_maybe=$([ -f "shell.nix" ] && echo "nix-shell")

TMUX="$(tmux new-session -d -s "$_session" -n project)"
tmux new-window -c "$_wd" -t "${_session}:1" -n build
tmux new-window -c "$_wd" -t "${_session}:2" -n git
tmux new-window -c "$_wd" -t "${_session}:3" -n mintette12
tmux new-window -c "$_wd" -t "${_session}:4" -n mintette34 
tmux new-window -c "$_wd" -t "${_session}:5" -n mintette56
tmux new-window -c "$_wd" -t "${_session}:6" -n mintette78
tmux new-window -c "$_wd" -t "${_session}:7" -n mintette9userd
tmux new-window -c "$_wd" -t "${_session}:8" -n bank

tmux send-keys -t "${_session}:0" "cd src/" C-m
tmux send-keys -t "${_session}:0" "vim ." C-m
tmux send-keys -t "${_session}:2" "git log --graph --decorate --all -n7 | grep ." C-m
if [ ! -z "$_post_hook_maybe" ]; then
  for x in {2..5}; do
    tmux send-keys -t "${_session}:${x}" "$_post_hook_maybe" C-m
  done
fi

tmux send-keys       -t "${_session}:3" "admin/runAsMintette.sh 1" C-m
tmux split-window -h -t "${_session}:3"
tmux send-keys       -t "${_session}:3" "sleep 1; admin/runAsMintette.sh 2" C-m

tmux send-keys       -t "${_session}:4" "sleep 2; admin/runAsMintette.sh 3" C-m
tmux split-window -h -t "${_session}:4"
tmux send-keys       -t "${_session}:4" "sleep 3; admin/runAsMintette.sh 4" C-m

tmux send-keys       -t "${_session}:5" "sleep 4; admin/runAsMintette.sh 5" C-m
tmux split-window -h -t "${_session}:5"
tmux send-keys       -t "${_session}:5" "sleep 5; admin/runAsMintette.sh 6" C-m

tmux send-keys       -t "${_session}:6" "sleep 6; admin/runAsMintette.sh 7" C-m
tmux split-window -h -t "${_session}:6"
tmux send-keys       -t "${_session}:6" "sleep 7; admin/runAsMintette.sh 8" C-m

tmux send-keys       -t "${_session}:7" "sleep 8; admin/runAsMintette.sh 9" C-m
tmux split-window -h -t "${_session}:7"
tmux send-keys       -t "${_session}:7" "sleep 12; admin/watchBlockchainUpdates.sh" C-m

# TODO: Spawn UI attached to wallet located at ./wallet-db-user down here ```````````````````````v
tmux send-keys       -t "${_session}:8" "sleep 11; admin/initDemoUser.sh demouser2-db demouser1-db && admin/initBankUser.sh && { rscoin-user start-gui --guidb-path=demouser1-gui-db --wallet-path=demouser2-db & rscoin-user start-gui --guidb-path=demouser2-gui-db --wallet-path=demouser1-db & }" C-m
tmux split-window -h -t "${_session}:8"
tmux send-keys       -t "${_session}:8" "sleep 10; rscoin-bank --log-severity Debug serve" C-m

tmux select-window -t 0

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t "${_session}"
else
  tmux -u switch-client -t "${_session}"
fi
